// swift-tools-version:5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// This file is generated by bin/scripts/megapackage/publish-megapackage.sh.
// Do not edit by hand: edit the template at bin/scripts/megapackage/Package.swift.template
// in the videocloud_agave repository instead.

import PackageDescription

let package = Package(
    name: "BrightcovePlayerSDK",
    platforms: [
        .iOS(.v14), .tvOS(.v15)
    ],
    products: [
        .library(
            name: "BrightcovePlayerSDK",
            targets: ["BrightcovePlayerSDKWrapper"]),
        .library(
            name: "BrightcoveIMA",
            targets: ["BrightcoveIMAWrapper"]),
        .library(
            name: "BrightcoveDAI",
            targets: ["BrightcoveDAIWrapper"]),
        .library(
            name: "BrightcoveFW",
            targets: ["BrightcoveFWWrapper"]),
        .library(
            name: "BrightcoveGoogleCast",
            targets: ["BrightcoveGoogleCastWrapper"]),
        .library(
            name: "BrightcoveAMC",
            targets: ["BrightcoveAMCWrapper"]),
        .library(
            name: "BrightcovePulse",
            targets: ["BrightcovePulseWrapper"]),
        .library(
            name: "BrightcoveSSAI",
            targets: ["BrightcoveSSAIWrapper"]),
        .library(
            name: "OMSDK_Brightcove",
            targets: ["OMSDK_BrightcoveWrapper"])
    ],
    dependencies: [
        .package(
            url: "https://github.com/googleads/swift-package-manager-google-interactive-media-ads-ios.git",
            .upToNextMinor(from: "3.26.1")),
        .package(
            url: "https://github.com/googleads/swift-package-manager-google-interactive-media-ads-tvos.git",
            .upToNextMinor(from: "4.16.0")),
        .package(
            url: "https://github.com/SRGSSR/google-cast-sdk.git",
            exact: "4.8.3")
    ],
    targets: [
        // Binary targets. Each is reached transitively through its wrapper target; none is
        // listed directly in a library product's targets: array.
        .binaryTarget(
            name: "BrightcovePlayerSDK",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.24/BrightcovePlayerSDK.xcframework.zip",
            checksum: "db59d31d9114228b8c279769b1e47675a4b53b5ad4254ebca5577a9ab3e104e4"),
        .binaryTarget(
            name: "BrightcoveIMA",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.24/BrightcoveIMA.xcframework.zip",
            checksum: "b5c52992fa9f18bdea2063a711461f70372531f6b71f0d05ca53d24c56cdf5e2"),
        .binaryTarget(
            name: "BrightcoveDAI",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.24/BrightcoveDAI.xcframework.zip",
            checksum: "88f200ff8e65c45415bf6635af9590c14c9561be57dace8d6ca3c8da610f0870"),
        .binaryTarget(
            name: "BrightcoveFW",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.24/BrightcoveFW.xcframework.zip",
            checksum: "a2b1b78caa0ff2fc81deee2803da95cc10a552ba0951ac9efbf354c78a9c9b66"),
        .binaryTarget(
            name: "BrightcoveGoogleCast",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.24/BrightcoveGoogleCast.xcframework.zip",
            checksum: "3d0e1d6dd46d1b5866d99ae4185e523cb4c23b4cb05db9436462732697c7cec9"),
        .binaryTarget(
            name: "BrightcoveAMC",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.24/BrightcoveAMC.xcframework.zip",
            checksum: "1f4cbe4fa2e778534f742cb6b738d0e3622a45548e74d708df1fbd929506aaee"),
        .binaryTarget(
            name: "BrightcovePulse",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.24/BrightcovePulse.xcframework.zip",
            checksum: "5d244965d632523068faa817a2b854148f1937407d6561c04e39456197b643d0"),
        .binaryTarget(
            name: "BrightcoveSSAI",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.24/BrightcoveSSAI.xcframework.zip",
            checksum: "b8af3c27d43ae28eb77dc2be862be7b1f3ad7ce35a8b16b43552ec878d72da96"),
        .binaryTarget(
            name: "OMSDK_Brightcove",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.24/OMSDK_Brightcove.xcframework.zip",
            checksum: "886a7b1cd5efddcb603bb9809c35d2570fab68b35e60cda72251c48ac62df648"),

        // Wrapper targets. Each carries the dependencies and linker settings that the
        // matching .binaryTarget cannot declare directly. The library products expose
        // only these wrappers.
        .target(
            name: "BrightcovePlayerSDKWrapper",
            dependencies: ["BrightcovePlayerSDK"],
            path: "Sources/BrightcovePlayerSDKWrapper"),
        .target(
            name: "BrightcoveIMAWrapper",
            dependencies: [
                "BrightcoveIMA",
                "BrightcovePlayerSDKWrapper",
                .product(name: "GoogleInteractiveMediaAds",
                         package: "swift-package-manager-google-interactive-media-ads-ios",
                         condition: .when(platforms: [.iOS])),
                .product(name: "GoogleInteractiveMediaAdsTvOS",
                         package: "swift-package-manager-google-interactive-media-ads-tvos",
                         condition: .when(platforms: [.tvOS]))
            ],
            path: "Sources/BrightcoveIMAWrapper"),
        .target(
            name: "BrightcoveDAIWrapper",
            dependencies: [
                "BrightcoveDAI",
                "BrightcovePlayerSDKWrapper",
                .product(name: "GoogleInteractiveMediaAds",
                         package: "swift-package-manager-google-interactive-media-ads-ios",
                         condition: .when(platforms: [.iOS])),
                .product(name: "GoogleInteractiveMediaAdsTvOS",
                         package: "swift-package-manager-google-interactive-media-ads-tvos",
                         condition: .when(platforms: [.tvOS]))
            ],
            path: "Sources/BrightcoveDAIWrapper"),
        .target(
            name: "BrightcoveFWWrapper",
            dependencies: ["BrightcoveFW", "BrightcovePlayerSDKWrapper"],
            path: "Sources/BrightcoveFWWrapper",
            linkerSettings: [
                .linkedLibrary("xml2"),
                .linkedFramework("AdSupport"),
                .linkedFramework("CoreLocation"),
                .linkedFramework("MessageUI", .when(platforms: [.iOS])),
                .linkedFramework("WebKit", .when(platforms: [.iOS]))
            ]),
        .target(
            name: "BrightcoveGoogleCastWrapper",
            dependencies: [
                "BrightcoveGoogleCast",
                "BrightcovePlayerSDKWrapper",
                .product(name: "GoogleCast", package: "google-cast-sdk")
            ],
            path: "Sources/BrightcoveGoogleCastWrapper"),
        .target(
            name: "BrightcoveAMCWrapper",
            dependencies: ["BrightcoveAMC", "BrightcovePlayerSDKWrapper"],
            path: "Sources/BrightcoveAMCWrapper",
            linkerSettings: [
                .linkedLibrary("sqlite3"),
                .linkedFramework("SystemConfiguration"),
                .linkedFramework("WebKit")
            ]),
        .target(
            name: "BrightcovePulseWrapper",
            dependencies: ["BrightcovePulse", "BrightcovePlayerSDKWrapper"],
            path: "Sources/BrightcovePulseWrapper"),
        .target(
            name: "BrightcoveSSAIWrapper",
            dependencies: ["BrightcoveSSAI", "BrightcovePlayerSDKWrapper"],
            path: "Sources/BrightcoveSSAIWrapper"),
        .target(
            name: "OMSDK_BrightcoveWrapper",
            dependencies: ["OMSDK_Brightcove"],
            path: "Sources/OMSDK_BrightcoveWrapper")
    ]
)
