// swift-tools-version:5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// This file is generated by bin/scripts/megapackage/publish-megapackage.sh.
// Do not edit by hand: edit the template at bin/scripts/megapackage/Package.swift.template
// in the videocloud_agave repository instead.

import PackageDescription

let package = Package(
    name: "BrightcovePlayerSDK",
    platforms: [
        .iOS(.v14), .tvOS(.v15)
    ],
    products: [
        .library(
            name: "BrightcovePlayerSDK",
            targets: ["BrightcovePlayerSDKWrapper"]),
        .library(
            name: "BrightcoveIMA",
            targets: ["BrightcoveIMAWrapper"]),
        .library(
            name: "BrightcoveDAI",
            targets: ["BrightcoveDAIWrapper"]),
        .library(
            name: "BrightcoveFW",
            targets: ["BrightcoveFWWrapper"]),
        .library(
            name: "BrightcoveGoogleCast",
            targets: ["BrightcoveGoogleCastWrapper"]),
        .library(
            name: "BrightcoveAMC",
            targets: ["BrightcoveAMCWrapper"]),
        .library(
            name: "BrightcovePulse",
            targets: ["BrightcovePulseWrapper"]),
        .library(
            name: "BrightcoveSSAI",
            targets: ["BrightcoveSSAIWrapper"]),
        .library(
            name: "OMSDK_Brightcove",
            targets: ["OMSDK_BrightcoveWrapper"])
    ],
    dependencies: [
        .package(
            url: "https://github.com/googleads/swift-package-manager-google-interactive-media-ads-ios.git",
            .upToNextMinor(from: "3.26.1")),
        .package(
            url: "https://github.com/googleads/swift-package-manager-google-interactive-media-ads-tvos.git",
            .upToNextMinor(from: "4.16.0")),
        .package(
            url: "https://github.com/SRGSSR/google-cast-sdk.git",
            exact: "4.8.3")
    ],
    targets: [
        // Binary targets. Each is reached transitively through its wrapper target; none is
        // listed directly in a library product's targets: array.
        .binaryTarget(
            name: "BrightcovePlayerSDK",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.23/BrightcovePlayerSDK.xcframework.zip",
            checksum: "554a24510893a63af5f9427f6fd05f2f1607f47871e4f5762c9f3a6682fe2ca4"),
        .binaryTarget(
            name: "BrightcoveIMA",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.23/BrightcoveIMA.xcframework.zip",
            checksum: "14724f054cebbc6800c6dbeb1fca72a911a5cc91f08c1dc90872a691bf52f630"),
        .binaryTarget(
            name: "BrightcoveDAI",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.23/BrightcoveDAI.xcframework.zip",
            checksum: "6e511fa2920a454537f985d13e58811b4b1b73db331148e63a108443af7e414a"),
        .binaryTarget(
            name: "BrightcoveFW",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.23/BrightcoveFW.xcframework.zip",
            checksum: "f06966b88fec1695787cb89258484262d65036272ef77322a6463b5ccc8f1d99"),
        .binaryTarget(
            name: "BrightcoveGoogleCast",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.23/BrightcoveGoogleCast.xcframework.zip",
            checksum: "65b248a80e4e0f97f424e632c710a0251917eab61a6f5ee9317886204b459ed3"),
        .binaryTarget(
            name: "BrightcoveAMC",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.23/BrightcoveAMC.xcframework.zip",
            checksum: "7cc58c07e75354c5bb0e1aeb6e4a3a79a92f9245e3e4d45843e34c2b0b32522d"),
        .binaryTarget(
            name: "BrightcovePulse",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.23/BrightcovePulse.xcframework.zip",
            checksum: "145665d6f0eec271b917cfd382eb12d7eff952ffa74636292b3d01ed691cac11"),
        .binaryTarget(
            name: "BrightcoveSSAI",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.23/BrightcoveSSAI.xcframework.zip",
            checksum: "9d6cfb80d612302e6812c8cade65e0f36e1c358e376d6601d12ade7111275f6d"),
        .binaryTarget(
            name: "OMSDK_Brightcove",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.23/OMSDK_Brightcove.xcframework.zip",
            checksum: "12213558e3b313112ffdb92bc813eb2dd1f2a945945bed1920171c13254e26e3"),

        // Wrapper targets. Each carries the dependencies and linker settings that the
        // matching .binaryTarget cannot declare directly. The library products expose
        // only these wrappers.
        .target(
            name: "BrightcovePlayerSDKWrapper",
            dependencies: ["BrightcovePlayerSDK"],
            path: "Sources/BrightcovePlayerSDKWrapper"),
        .target(
            name: "BrightcoveIMAWrapper",
            dependencies: [
                "BrightcoveIMA",
                "BrightcovePlayerSDKWrapper",
                .product(name: "GoogleInteractiveMediaAds",
                         package: "swift-package-manager-google-interactive-media-ads-ios",
                         condition: .when(platforms: [.iOS])),
                .product(name: "GoogleInteractiveMediaAdsTvOS",
                         package: "swift-package-manager-google-interactive-media-ads-tvos",
                         condition: .when(platforms: [.tvOS]))
            ],
            path: "Sources/BrightcoveIMAWrapper"),
        .target(
            name: "BrightcoveDAIWrapper",
            dependencies: [
                "BrightcoveDAI",
                "BrightcovePlayerSDKWrapper",
                .product(name: "GoogleInteractiveMediaAds",
                         package: "swift-package-manager-google-interactive-media-ads-ios",
                         condition: .when(platforms: [.iOS])),
                .product(name: "GoogleInteractiveMediaAdsTvOS",
                         package: "swift-package-manager-google-interactive-media-ads-tvos",
                         condition: .when(platforms: [.tvOS]))
            ],
            path: "Sources/BrightcoveDAIWrapper"),
        .target(
            name: "BrightcoveFWWrapper",
            dependencies: ["BrightcoveFW", "BrightcovePlayerSDKWrapper"],
            path: "Sources/BrightcoveFWWrapper",
            linkerSettings: [
                .linkedLibrary("xml2"),
                .linkedFramework("AdSupport"),
                .linkedFramework("CoreLocation"),
                .linkedFramework("MessageUI", .when(platforms: [.iOS])),
                .linkedFramework("WebKit", .when(platforms: [.iOS]))
            ]),
        .target(
            name: "BrightcoveGoogleCastWrapper",
            dependencies: [
                "BrightcoveGoogleCast",
                "BrightcovePlayerSDKWrapper",
                .product(name: "GoogleCast", package: "google-cast-sdk")
            ],
            path: "Sources/BrightcoveGoogleCastWrapper"),
        .target(
            name: "BrightcoveAMCWrapper",
            dependencies: ["BrightcoveAMC", "BrightcovePlayerSDKWrapper"],
            path: "Sources/BrightcoveAMCWrapper",
            linkerSettings: [
                .linkedLibrary("sqlite3"),
                .linkedFramework("SystemConfiguration"),
                .linkedFramework("WebKit")
            ]),
        .target(
            name: "BrightcovePulseWrapper",
            dependencies: ["BrightcovePulse", "BrightcovePlayerSDKWrapper"],
            path: "Sources/BrightcovePulseWrapper"),
        .target(
            name: "BrightcoveSSAIWrapper",
            dependencies: ["BrightcoveSSAI", "BrightcovePlayerSDKWrapper"],
            path: "Sources/BrightcoveSSAIWrapper"),
        .target(
            name: "OMSDK_BrightcoveWrapper",
            dependencies: ["OMSDK_Brightcove"],
            path: "Sources/OMSDK_BrightcoveWrapper")
    ]
)
