// swift-tools-version:5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// This file is generated by bin/scripts/megapackage/publish-megapackage.sh.
// Do not edit by hand: edit the template at bin/scripts/megapackage/Package.swift.template
// in the videocloud_agave repository instead.

import PackageDescription

let package = Package(
    name: "BrightcovePlayerSDK",
    platforms: [
        .iOS(.v14), .tvOS(.v15)
    ],
    products: [
        .library(
            name: "BrightcovePlayerSDK",
            targets: ["BrightcovePlayerSDKWrapper"]),
        .library(
            name: "BrightcoveIMA",
            targets: ["BrightcoveIMAWrapper"]),
        .library(
            name: "BrightcoveDAI",
            targets: ["BrightcoveDAIWrapper"]),
        .library(
            name: "BrightcoveFW",
            targets: ["BrightcoveFWWrapper"]),
        .library(
            name: "BrightcoveGoogleCast",
            targets: ["BrightcoveGoogleCastWrapper"]),
        .library(
            name: "BrightcoveAMC",
            targets: ["BrightcoveAMCWrapper"]),
        .library(
            name: "BrightcovePulse",
            targets: ["BrightcovePulseWrapper"]),
        .library(
            name: "BrightcoveSSAI",
            targets: ["BrightcoveSSAIWrapper"]),
        .library(
            name: "OMSDK_Brightcove",
            targets: ["OMSDK_BrightcoveWrapper"])
    ],
    dependencies: [
        .package(
            url: "https://github.com/googleads/swift-package-manager-google-interactive-media-ads-ios.git",
            .upToNextMinor(from: "3.26.1")),
        .package(
            url: "https://github.com/googleads/swift-package-manager-google-interactive-media-ads-tvos.git",
            .upToNextMinor(from: "4.16.0")),
        .package(
            url: "https://github.com/SRGSSR/google-cast-sdk.git",
            exact: "4.8.3")
    ],
    targets: [
        // Binary targets. Each is reached transitively through its wrapper target; none is
        // listed directly in a library product's targets: array.
        .binaryTarget(
            name: "BrightcovePlayerSDK",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.19/BrightcovePlayerSDK.xcframework.zip",
            checksum: "f7fc36412ce7042fd2133dc9f68a25e36fb899645a8f2ec59fc91b70aeaf63c5"),
        .binaryTarget(
            name: "BrightcoveIMA",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.19/BrightcoveIMA.xcframework.zip",
            checksum: "8c9f4051088d2271dee0ebeb611ac3f8c52610150390e92f9b8f99e1780ee074"),
        .binaryTarget(
            name: "BrightcoveDAI",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.19/BrightcoveDAI.xcframework.zip",
            checksum: "51eaf70d2ac905802823b737e084b59412dc556d30f4c4669fdbedd021a971c9"),
        .binaryTarget(
            name: "BrightcoveFW",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.19/BrightcoveFW.xcframework.zip",
            checksum: "9122a80d72b1b0a9d597bdf1ee3d62c848ca060b80ba562001b8f35addb339b5"),
        .binaryTarget(
            name: "BrightcoveGoogleCast",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.19/BrightcoveGoogleCast.xcframework.zip",
            checksum: "862b865e0931a4d8485e12ebc38b03a3109dbc0be5334cd68e6ef2986074e7b2"),
        .binaryTarget(
            name: "BrightcoveAMC",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.19/BrightcoveAMC.xcframework.zip",
            checksum: "7185e9f765af991d509d77ea5188695c0909993e1c0557bf591e3d94485965db"),
        .binaryTarget(
            name: "BrightcovePulse",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.19/BrightcovePulse.xcframework.zip",
            checksum: "519d1505beb9ce3745832c182a6c71fca9e7d4c2f19bba730c9dfc23ec7d3b72"),
        .binaryTarget(
            name: "BrightcoveSSAI",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.19/BrightcoveSSAI.xcframework.zip",
            checksum: "89e45e85afadbf6b548aa10511846bd3c6d1ab7cb90d50837515eee5f84dd05d"),
        .binaryTarget(
            name: "OMSDK_Brightcove",
            url: "https://github.com/brightcove/brightcove-player-sdk-ios/releases/download/v7.2.19/OMSDK_Brightcove.xcframework.zip",
            checksum: "789a15163204f3bea14208901e004c3298e5dcc43586e92199409bb7c83b75b1"),

        // Wrapper targets. Each carries the dependencies and linker settings that the
        // matching .binaryTarget cannot declare directly. The library products expose
        // only these wrappers.
        .target(
            name: "BrightcovePlayerSDKWrapper",
            dependencies: ["BrightcovePlayerSDK"],
            path: "Sources/BrightcovePlayerSDKWrapper"),
        .target(
            name: "BrightcoveIMAWrapper",
            dependencies: [
                "BrightcoveIMA",
                "BrightcovePlayerSDKWrapper",
                .product(name: "GoogleInteractiveMediaAds",
                         package: "swift-package-manager-google-interactive-media-ads-ios",
                         condition: .when(platforms: [.iOS])),
                .product(name: "GoogleInteractiveMediaAdsTvOS",
                         package: "swift-package-manager-google-interactive-media-ads-tvos",
                         condition: .when(platforms: [.tvOS]))
            ],
            path: "Sources/BrightcoveIMAWrapper"),
        .target(
            name: "BrightcoveDAIWrapper",
            dependencies: [
                "BrightcoveDAI",
                "BrightcovePlayerSDKWrapper",
                .product(name: "GoogleInteractiveMediaAds",
                         package: "swift-package-manager-google-interactive-media-ads-ios",
                         condition: .when(platforms: [.iOS])),
                .product(name: "GoogleInteractiveMediaAdsTvOS",
                         package: "swift-package-manager-google-interactive-media-ads-tvos",
                         condition: .when(platforms: [.tvOS]))
            ],
            path: "Sources/BrightcoveDAIWrapper"),
        .target(
            name: "BrightcoveFWWrapper",
            dependencies: ["BrightcoveFW", "BrightcovePlayerSDKWrapper"],
            path: "Sources/BrightcoveFWWrapper",
            linkerSettings: [
                .linkedLibrary("xml2"),
                .linkedFramework("AdSupport"),
                .linkedFramework("CoreLocation"),
                .linkedFramework("MessageUI", .when(platforms: [.iOS])),
                .linkedFramework("WebKit", .when(platforms: [.iOS]))
            ]),
        .target(
            name: "BrightcoveGoogleCastWrapper",
            dependencies: [
                "BrightcoveGoogleCast",
                "BrightcovePlayerSDKWrapper",
                .product(name: "GoogleCast", package: "google-cast-sdk")
            ],
            path: "Sources/BrightcoveGoogleCastWrapper"),
        .target(
            name: "BrightcoveAMCWrapper",
            dependencies: ["BrightcoveAMC", "BrightcovePlayerSDKWrapper"],
            path: "Sources/BrightcoveAMCWrapper",
            linkerSettings: [
                .linkedLibrary("sqlite3"),
                .linkedFramework("SystemConfiguration"),
                .linkedFramework("WebKit")
            ]),
        .target(
            name: "BrightcovePulseWrapper",
            dependencies: ["BrightcovePulse", "BrightcovePlayerSDKWrapper"],
            path: "Sources/BrightcovePulseWrapper"),
        .target(
            name: "BrightcoveSSAIWrapper",
            dependencies: ["BrightcoveSSAI", "BrightcovePlayerSDKWrapper"],
            path: "Sources/BrightcoveSSAIWrapper"),
        .target(
            name: "OMSDK_BrightcoveWrapper",
            dependencies: ["OMSDK_Brightcove"],
            path: "Sources/OMSDK_BrightcoveWrapper")
    ]
)
